#
###################################
# Site wide configuration
####################################
#
title: Minjeong
email: jmakeaz@gmail.com
description: For what it's worth, it's never too late or too early to be whoever you want to be.
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Korea/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Minjeong
  avatar: happy.png
  job: "Front end developer"
  bio: "For what it's worth, it's never too late or too early to be whoever you want to be."
  email: jmakeaz@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jin-2
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
