# Site settings
title: Jmaking
email: jmakeaz@gmail.com
description: > # Everything about the front-end.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
#  Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
#  Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
#  About : ['About', '/about', 'fa-heart']
#  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/jmaking', 'fa-heart']
single_footer: '<p>I am a slow walker, but I never walk back.</p>'
footer_links:
    About: ['Copyright (c) 2015 Jmaking All Rights Reserved.', '#']
    #Writer: ['Writer 2015', '/about']

# 포스트 머리말 기본값 정의
defaults:
  -
    scope:
      path: "" # 이 빈 문자열은 프로젝트 내의 모든 파일을 의미한다
      type: "posts" # 과거 Jekyll 2.2 의 `post`.
    values:
      layout: "post"
      author_name: jmaking
      author_url: /author/jmaking
      author_avatar: jmaking
      read_time: 30
      show_related_posts: true
      show_avatar: false

# Build settings
markdown: kramdown

# Sass
sass:
    style: compact
    sourcemap : true
